name: Cleanup Pull Requests

on:
  push:
    branches:
      - trunk
      - '3.[89]'
      - '[4-9].[0-9]'
      - test-close-prs
  schedule:
    - cron: '0 */12 * * *'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  # Runs the QUnit tests for WordPress.
  #
  # Performs the following steps:
  # - Checks out the repository.
  close-prs-push:
    name: Close pull requests on commit
    runs-on: ubuntu-latest
#    if: ${{ github.repository == 'WordPress/wordpress-develop' && github.event_name == 'push' }}

    steps:
      - name: Parse commit message
        id: fixed-tickets
        run: |
          COMMIT_MESSAGE=$(cat <<'EOF' | sed -n '/^Fixes #/,/\./p'
          ${{ github.event.head_commit.message }}
          EOF
          )
          echo "::set-output name=fixed_list::${COMMIT_MESSAGE}"

      - name: Create search query
        id: pr-query
        uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667 # v5.0.0
        with:
          script: |
            const fixesLine = "${{ steps.fixed-tickets.outputs.fixed_list }}";
            let ticketList = false;
            let query = '';
            ticketList = fixesLine.match( /[0-9]+/g );

            if ( ticketList && ticketList.length > 0 ) {
              query += 'is:pr is:open in:title,body repo:WordPress/wordpress-develop';
              let tempQuery = query;

              ticketList.every( ( value, index ) => {
                if ( 0 !== index ) {
                  tempQuery += ' OR';
                }

                tempQuery += ` https://core.trac.wordpress.org/ticket/${value}`;

                if ( tempQuery.length <= 256 ) {
                  query = tempQuery;
                  return true;
                } else {
                  return false;
                }
              });
            }

            return query;

      - name: Find pull requests
        id: pr-results
        uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667 # v5.0.0
        with:
          script: |
            const related_prs = await github.rest.search.issuesAndPullRequests({
              q: ${{ steps.pr-query.outputs.result }},
            });

            return related_prs && related_prs.items;

      - name: Get git-svn-id
        id: git-svn-id
        run: |
          COMMIT_MESSAGE=$(cat <<'EOF' | sed -n '$p'
          ${{ github.event.head_commit.message }}
          EOF
          )
          echo "::set-output name=svn_revision_number::${COMMIT_MESSAGE}"

      - name: Close pull requests
        uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667 # v5.0.0
        with:
          script: |
            const gitSVNIDString = '${{ steps.git-svn-id.outputs.svn_revision_number }}';

            const revisionMatch = gitSVNIDString.match( /develop\.svn\.wordpress\.org\/trunk@([0-9]+)\s.*/ig );

            if ( revisionMatch ) {
              console.log({revisionMatch})
            }

            // const prsToClose = ${{ steps.pr-results.outputs.result }}

            // prsToClose.forEach( ( { owner, repo, number } ) => {
              // const comment = await github.rest.issues.createComment( {
                // owner,
                // repo,
                // pull_number: number,
                // body: inputs.comment
              // } );

              // const close = await github.rest.pulls.update( {
                // owner: pr.owner,
                // repo: pr.repo,
                // pull_number: pr.number,
                // state: 'closed'
              // } )
            // } );

